const express = require("express");
const cors = require("cors");

const app = express();
app.use(cors());
app.use(express.json());

/**
 * game_topic_id
 * 1 = Java
 * 2 = Python
 * 3 = Cloud
 *
 * correct_answer must be "1" | "2" | "3" | "4" (string) to match your screenshot
 */
const QUESTIONS = [
  // -------------------- JAVA (1) --------------------
  {
    game_topic_id: 1,
    question_id: 1,
    question: "What is the main purpose of the JVM?",
    answer_1: "To compile Java source code directly to machine code",
    answer_2: "To execute Java bytecode and provide platform independence",
    answer_3: "To replace the operating system",
    answer_4: "To store Java objects permanently",
    correct_answer: "2",
    available_time_limit: 30,
  },
  {
    game_topic_id: 1,
    question_id: 2,
    question: "Which keyword is used to inherit a class in Java?",
    answer_1: "implements",
    answer_2: "inherits",
    answer_3: "extends",
    answer_4: "super",
    correct_answer: "3",
    available_time_limit: 30,
  },
  {
    game_topic_id: 1,
    question_id: 3,
    question: "What does 'final' mean for a variable in Java?",
    answer_1: "It can be changed once",
    answer_2: "It cannot be reassigned after initialization",
    answer_3: "It is stored only in heap",
    answer_4: "It is thread-safe automatically",
    correct_answer: "2",
    available_time_limit: 30,
  },
  {
    game_topic_id: 1,
    question_id: 4,
    question: "Which collection does NOT allow duplicates?",
    answer_1: "List",
    answer_2: "Set",
    answer_3: "ArrayList",
    answer_4: "LinkedList",
    correct_answer: "2",
    available_time_limit: 30,
  },
  {
    game_topic_id: 1,
    question_id: 5,
    question: "What is method overloading?",
    answer_1: "Same method name with same parameters but different return type only",
    answer_2: "Same method name with different parameter list",
    answer_3: "Different method name with same parameters",
    answer_4: "Overriding private methods",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 1,
    question_id: 6,
    question: "What is the default value of an uninitialized int field in a Java class?",
    answer_1: "null",
    answer_2: "0",
    answer_3: "undefined",
    answer_4: "1",
    correct_answer: "2",
    available_time_limit: 25,
  },
  {
    game_topic_id: 1,
    question_id: 7,
    question: "Which statement about interfaces is TRUE (Java 8+)?",
    answer_1: "Interfaces cannot have any method implementations",
    answer_2: "Interfaces can have default and static methods",
    answer_3: "Interfaces can extend classes",
    answer_4: "A class can implement only one interface",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 1,
    question_id: 8,
    question: "What is the time complexity of HashMap get() on average?",
    answer_1: "O(n)",
    answer_2: "O(log n)",
    answer_3: "O(1)",
    answer_4: "O(n log n)",
    correct_answer: "3",
    available_time_limit: 35,
  },
  {
    game_topic_id: 1,
    question_id: 9,
    question: "Which exception is unchecked?",
    answer_1: "IOException",
    answer_2: "SQLException",
    answer_3: "NullPointerException",
    answer_4: "ClassNotFoundException",
    correct_answer: "3",
    available_time_limit: 30,
  },
  {
    game_topic_id: 1,
    question_id: 10,
    question: "What does 'synchronized' do for a method?",
    answer_1: "Makes it run faster",
    answer_2: "Ensures mutual exclusion using the object's monitor/lock",
    answer_3: "Prevents garbage collection",
    answer_4: "Allows parallel writes without locking",
    correct_answer: "2",
    available_time_limit: 45,
  },
  {
    game_topic_id: 1,
    question_id: 11,
    question: "What is the main difference between == and equals() for objects?",
    answer_1: "No difference",
    answer_2: "== compares references, equals() compares logical equality (if overridden)",
    answer_3: "== compares values, equals() compares references",
    answer_4: "equals() works only for Strings",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 1,
    question_id: 12,
    question: "Which is TRUE about Java garbage collection?",
    answer_1: "It guarantees immediate memory release",
    answer_2: "It automatically frees unreachable objects",
    answer_3: "It deletes objects in a fixed order",
    answer_4: "It requires manual free() calls",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 1,
    question_id: 13,
    question: "What is a functional interface?",
    answer_1: "An interface with no methods",
    answer_2: "An interface with exactly one abstract method",
    answer_3: "An interface with only static methods",
    answer_4: "An interface that cannot be implemented",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 1,
    question_id: 14,
    question: "Which Java feature helps achieve runtime polymorphism?",
    answer_1: "Method overloading",
    answer_2: "Method overriding",
    answer_3: "Constructor chaining",
    answer_4: "Static binding",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 1,
    question_id: 15,
    question: "In Java, what is 'volatile' mainly used for?",
    answer_1: "Atomicity of operations",
    answer_2: "Ensuring visibility of changes across threads",
    answer_3: "Preventing deadlocks",
    answer_4: "Making methods synchronized automatically",
    correct_answer: "2",
    available_time_limit: 50,
  },
  {
    game_topic_id: 1,
    question_id: 16,
    question: "What does Stream API primarily enable?",
    answer_1: "Direct file streaming only",
    answer_2: "Functional-style operations on collections of data",
    answer_3: "Low-level thread management",
    answer_4: "Replacing all loops at runtime",
    correct_answer: "2",
    available_time_limit: 45,
  },
  // -------------------- PYTHON (2) --------------------
  {
    game_topic_id: 2,
    question_id: 17,
    question: "What is the output of: bool([]) in Python?",
    answer_1: "True",
    answer_2: "False",
    answer_3: "[]",
    answer_4: "Error",
    correct_answer: "2",
    available_time_limit: 25,
  },
  {
    game_topic_id: 2,
    question_id: 18,
    question: "Which data type is immutable in Python?",
    answer_1: "list",
    answer_2: "dict",
    answer_3: "set",
    answer_4: "tuple",
    correct_answer: "4",
    available_time_limit: 30,
  },
  {
    game_topic_id: 2,
    question_id: 19,
    question: "What does *args represent in a function definition?",
    answer_1: "Keyword arguments as dict",
    answer_2: "Variable-length positional arguments as tuple",
    answer_3: "A pointer to arguments",
    answer_4: "A list of default values",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 2,
    question_id: 20,
    question: "What is a Python generator?",
    answer_1: "A function that returns a list always",
    answer_2: "A function that uses yield to produce values lazily",
    answer_3: "A class that generates random numbers only",
    answer_4: "A module for code compilation",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 2,
    question_id: 21,
    question: "What does GIL stand for in CPython?",
    answer_1: "Global Interpreter Lock",
    answer_2: "General Instruction List",
    answer_3: "Graphical Interface Layer",
    answer_4: "Global Import Loader",
    correct_answer: "1",
    available_time_limit: 45,
  },
  {
    game_topic_id: 2,
    question_id: 22,
    question: "Which statement about list comprehension is TRUE?",
    answer_1: "It is always slower than a for-loop",
    answer_2: "It can be used to create a new list from an iterable",
    answer_3: "It modifies the original list in-place only",
    answer_4: "It works only with integers",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 2,
    question_id: 23,
    question: "What is the difference between deep copy and shallow copy?",
    answer_1: "No difference",
    answer_2: "Shallow copies nested references; deep copy duplicates nested objects",
    answer_3: "Deep copy is only for strings",
    answer_4: "Shallow copy is slower always",
    correct_answer: "2",
    available_time_limit: 50,
  },
  {
    game_topic_id: 2,
    question_id: 24,
    question: "What is the result of: 'a' in {'a': 1} ?",
    answer_1: "Checks if key exists (True)",
    answer_2: "Checks if value exists",
    answer_3: "Returns 1",
    answer_4: "Raises KeyError",
    correct_answer: "1",
    available_time_limit: 30,
  },
  {
    game_topic_id: 2,
    question_id: 25,
    question: "What is the purpose of a context manager (with statement)?",
    answer_1: "To speed up loops",
    answer_2: "To manage setup/teardown like opening/closing resources safely",
    answer_3: "To prevent exceptions from ever happening",
    answer_4: "To create threads automatically",
    correct_answer: "2",
    available_time_limit: 45,
  },
  {
    game_topic_id: 2,
    question_id: 26,
    question: "Which of these is TRUE about Python's typing hints?",
    answer_1: "They are enforced at runtime by default",
    answer_2: "They are mainly for readability and static analysis tools",
    answer_3: "They replace unit tests",
    answer_4: "They make code compile to C automatically",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 2,
    question_id: 27,
    question: "What happens if you modify a list while iterating over it?",
    answer_1: "Always safe",
    answer_2: "Can cause unexpected behavior (skipped/duplicated items)",
    answer_3: "Python throws a compile-time error",
    answer_4: "The list becomes immutable",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 2,
    question_id: 28,
    question: "What does __init__ do in a Python class?",
    answer_1: "Deletes the object",
    answer_2: "Initializes a newly created instance",
    answer_3: "Creates a static method",
    answer_4: "Imports required modules",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 2,
    question_id: 29,
    question: "What is the time complexity of dict key lookup on average?",
    answer_1: "O(n)",
    answer_2: "O(1)",
    answer_3: "O(log n)",
    answer_4: "O(n log n)",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 2,
    question_id: 30,
    question: "Which is a correct way to handle exceptions?",
    answer_1: "try...catch",
    answer_2: "try...except",
    answer_3: "catch...finally",
    answer_4: "except...try",
    correct_answer: "2",
    available_time_limit: 30,
  },
  {
    game_topic_id: 2,
    question_id: 31,
    question: "What is a Python decorator?",
    answer_1: "A tool to decorate terminal output",
    answer_2: "A function that takes another function and extends/changes its behavior",
    answer_3: "A syntax error",
    answer_4: "A built-in class for inheritance",
    correct_answer: "2",
    available_time_limit: 50,
  },
  {
    game_topic_id: 2,
    question_id: 32,
    question: "In async Python, what does await do?",
    answer_1: "Blocks the OS thread permanently",
    answer_2: "Pauses coroutine until awaited task completes, allowing other tasks to run",
    answer_3: "Creates a new process",
    answer_4: "Disables concurrency",
    correct_answer: "2",
    available_time_limit: 55,
  },
  // -------------------- CLOUD (3) --------------------
  {
    game_topic_id: 3,
    question_id: 33,
    question: "What is the main benefit of auto-scaling in cloud?",
    answer_1: "It guarantees zero downtime always",
    answer_2: "It automatically adjusts resources based on demand",
    answer_3: "It removes the need for networking",
    answer_4: "It replaces CI/CD",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 3,
    question_id: 34,
    question: "Which service model provides managed runtime but not OS management?",
    answer_1: "IaaS",
    answer_2: "PaaS",
    answer_3: "SaaS",
    answer_4: "On-prem",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 3,
    question_id: 35,
    question: "What does 'stateless' mean for cloud applications?",
    answer_1: "They never store data anywhere",
    answer_2: "State is not stored in the instance; can be scaled horizontally easily",
    answer_3: "They only run on one server",
    answer_4: "They cannot use databases",
    correct_answer: "2",
    available_time_limit: 45,
  },
  {
    game_topic_id: 3,
    question_id: 36,
    question: "What is a primary purpose of a VPC (Virtual Private Cloud)?",
    answer_1: "To host Git repositories",
    answer_2: "To provide isolated virtual network in the cloud",
    answer_3: "To replace DNS",
    answer_4: "To compress files",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 37,
    question: "What is an SLA in cloud services?",
    answer_1: "Software License Agreement",
    answer_2: "Service Level Agreement defining uptime/support commitments",
    answer_3: "Secure Login Authentication",
    answer_4: "Storage Limit Allocation",
    correct_answer: "2",
    available_time_limit: 35,
  },
  {
    game_topic_id: 3,
    question_id: 38,
    question: "Which is best for storing secrets like API keys?",
    answer_1: "Hardcode in source code",
    answer_2: "Commit into git",
    answer_3: "Use a secret manager service",
    answer_4: "Share in chat",
    correct_answer: "3",
    available_time_limit: 35,
  },
  {
    game_topic_id: 3,
    question_id: 39,
    question: "What is a CDN primarily used for?",
    answer_1: "Running databases",
    answer_2: "Serving content from edge locations to reduce latency",
    answer_3: "Building Docker images",
    answer_4: "Managing IAM users",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 40,
    question: "Which is an advantage of containers over VMs?",
    answer_1: "Containers virtualize hardware more fully",
    answer_2: "Containers are lighter and start faster by sharing host OS kernel",
    answer_3: "Containers require more RAM always",
    answer_4: "Containers cannot be orchestrated",
    correct_answer: "2",
    available_time_limit: 45,
  },
  {
    game_topic_id: 3,
    question_id: 41,
    question: "What problem does Kubernetes primarily solve?",
    answer_1: "Writing application code",
    answer_2: "Orchestrating containers (deploy, scale, heal)",
    answer_3: "Replacing Git",
    answer_4: "Generating UI designs",
    correct_answer: "2",
    available_time_limit: 50,
  },
  {
    game_topic_id: 3,
    question_id: 42,
    question: "What is 'Infrastructure as Code' (IaC)?",
    answer_1: "Writing infrastructure configs in code for repeatable provisioning",
    answer_2: "A new programming language",
    answer_3: "Manual server setup",
    answer_4: "Only used for frontend",
    correct_answer: "1",
    available_time_limit: 45,
  },
  {
    game_topic_id: 3,
    question_id: 43,
    question: "Which storage is best for highly durable object storage?",
    answer_1: "Object Storage (like S3/Blob Storage)",
    answer_2: "Local disk only",
    answer_3: "CPU cache",
    answer_4: "Swap memory",
    correct_answer: "1",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 44,
    question: "What is a 'blue-green deployment'?",
    answer_1: "Deploy only at night",
    answer_2: "Two identical environments; switch traffic to reduce downtime risk",
    answer_3: "Deploy without testing",
    answer_4: "A network routing protocol",
    correct_answer: "2",
    available_time_limit: 50,
  },
  {
    game_topic_id: 3,
    question_id: 45,
    question: "What is the purpose of IAM in cloud?",
    answer_1: "To store images",
    answer_2: "To manage identities, roles, and permissions",
    answer_3: "To build CI pipelines",
    answer_4: "To monitor CPU temperature",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 46,
    question: "What is the best practice for least privilege?",
    answer_1: "Give admin access to everyone",
    answer_2: "Grant only necessary permissions required for tasks",
    answer_3: "Share one root account",
    answer_4: "Disable MFA",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 47,
    question: "Which is a common cloud monitoring metric?",
    answer_1: "Keyboard typing speed",
    answer_2: "CPU utilization",
    answer_3: "Monitor brightness",
    answer_4: "Desk temperature",
    correct_answer: "2",
    available_time_limit: 30,
  },
  {
    game_topic_id: 3,
    question_id: 48,
    question: "What is a major reason to use multi-AZ/region architecture?",
    answer_1: "To increase code size",
    answer_2: "To improve availability and disaster recovery",
    answer_3: "To reduce encryption",
    answer_4: "To avoid load balancers",
    correct_answer: "2",
    available_time_limit: 45,
  },
  {
    game_topic_id: 3,
    question_id: 49,
    question: "In cloud security, what is encryption at rest?",
    answer_1: "Encrypting data while it travels on network",
    answer_2: "Encrypting stored data on disk/storage",
    answer_3: "Encrypting only passwords",
    answer_4: "No encryption needed",
    correct_answer: "2",
    available_time_limit: 40,
  },
  {
    game_topic_id: 3,
    question_id: 50,
    question: "What is a key advantage of serverless computing?",
    answer_1: "You manage servers manually",
    answer_2: "Automatic scaling and pay-per-use execution model",
    answer_3: "Requires fixed monthly cost always",
    answer_4: "Cannot connect to databases",
    correct_answer: "2",
    available_time_limit: 45,
  },
];

// Health check
app.get("/", (req, res) => {
  res.json({ status: "ok", service: "mcq-api" });
});

// Random question endpoint (like your screenshot)
app.get("/api/question", (req, res) => {
  const randomIndex = Math.floor(Math.random() * QUESTIONS.length);
  //res.json(QUESTIONS[randomIndex]);
  setTimeout(() => {
    res.json(QUESTIONS[randomIndex]);
  }, 200);
});

// Optional: filter by topic: /api/question?topic=1
app.get("/api/question-by-topic", (req, res) => {
  const topic = Number(req.query.topic);
  if (![1, 2, 3].includes(topic)) {
    return res.status(400).json({ error: "topic must be 1 (Java), 2 (Python), or 3 (Cloud)" });
  }
  const pool = QUESTIONS.filter((q) => q.game_topic_id === topic);
  const randomIndex = Math.floor(Math.random() * pool.length);
  res.json(pool[randomIndex]);
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`MCQ API running on http://localhost:${PORT}`));
